#!/bin/sh

check() {
    mail -H 2>/dev/null | \
	awk '
    NR == 2 {
        for (i = 5; i <= NF; i += 2) {
	    if ($i == "new") new = $(i - 1)
	    else if ($i == "unread") unread = $(i - 1)
	}
	exit
    }

    END {
        if (new > 0) print "new"
	else if (unread > 0) print "unread"
	else print "nil"
    }'
    wait_on "$MAIL"
}

while true; do check; done | \
while read status; do
  case $status in
    new)
      echo 'mymailbox:set_markup("<span foreground=\"red\" font_size=\"20000\" font_weight=\"bold\">'$'\u2709''</span>")' | awesome-client
      ;;
    unread)
      echo 'mymailbox:set_markup("<span foreground=\"yellow\" font_size=\"20000\">'$'\u2709''</span>")' | awesome-client
      ;;
    *)
      echo 'mymailbox:set_text("")' | awesome-client
  esac
done
