#!/bin/sh

# awesome-mailcheck
#    Watches the users mailbox and sends a command to
#    the awesome window manager to display a text in a widget
#    every time the mailbox changes.
#
# Add the following code to ~/.config/awesome/rc.lua to activate this script
#
#    mymailbox = wibox.widget.textbox()

#    local mailcheck_pid_file="/path/to/home/directory/.awesome-mailcheck.pid"
#    os.execute("daemon -P "..mailcheck_pid_file.." /path/to/script/awesome-mailcheck")
#
#    awesome.connect_signal("exit", function()
#      local file = io.open(mailcheck_pid_file, "r")
#      local pgid
#      if file then pgid = file:read("*l") end
#      os.execute("/bin/kill -- -"..pgid)
#    end)

new_text='mymailbox:set_markup(\"<span foreground=\\\"red\\\" font_size=\\\"18000\\\" font_weight=\\\"bold\\\">'$'\u2709''</span>\")'

unread_text='mymailbox:set_markup(\"<span foreground=\\\"yellow\\\" font_size=\\\"18000\\\">'$'\u2709''</span>\")'

nil_text='mymailbox:set_text(\"\")'

awk_source='
    NR == 2 {
	for (i = 5; i <= NF; i += 2) {
	    if ($i == "new") new = $(i - 1)
	    else if ($i == "unread") unread = $(i - 1)
	}
	exit
    }

    END {
	if (new > 0) print "'"$new_text"'"
	else if (unread > 0) print "'"$unread_text"'"
	else print "'"$nil_text"'"
    }'

while true; do
    mail -H 2>/dev/null | awk "$awk_source" | awesome-client
    wait_on "$MAIL"
done
